name: tradelait
description: Tradelait - Forex Signals, Crypto Signals, Trade Buddy.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.6+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  provider: ^6.0.1
   
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  in_app_review: ^2.0.3
  url_launcher: ^6.0.12
  google_sign_in: ^5.1.1
  scrollable_positioned_list: ^0.3.1
  flutter_typeahead: ^3.2.1
  font_awesome_flutter: ^10.1.0

  # generate fake user data
  faker: ^2.0.0-rc.2

  esc_pos_utils: ^1.1.0
  bluetooth_thermal_printer: ^0.0.6

  carousel_slider: ^4.0.0
  flutter_keyboard_visibility_web: ^2.0.0
  http: ^0.13.4
  oktoast: ^3.1.5
  qr_flutter: ^4.0.0
  path_provider: ^2.0.7
  linkfive_purchases: ^2.0.2
  linkfive_purchases_provider: ^2.0.2

   

dev_dependencies:
  flutter_test:
    sdk: flutter

    
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/page_images/
    

